name: objdet
channels:
  - defaults
dependencies:
  - ipykernel=6.29.5
  - ipython=8.12.2
  - matplotlib=3.7.2
  - numpy=1.24.3
  - opencv=4.10.0
  - pillow=10.4.0
  - pip=24.2
  - python=3.8.20
  - scikit-learn=1.3.0
  - scipy=1.10.1
  - pip:
    - dvc==3.42.0
    - dvc-gdrive==3.0.1
