name: objdet
channels:
  - defaults
dependencies:
  - appnope=0.1.2
  - asttokens=2.0.5
  - backcall=0.2.0
  - blas=1.0
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - c-ares=1.19.1
  - ca-certificates=2025.2.25
  - cairo=1.16.0
  - certifi=2024.8.30
  - charset-normalizer=3.3.2
  - comm=0.2.1
  - contourpy=1.0.5
  - cycler=0.11.0
  - cyrus-sasl=2.1.28
  - debugpy=1.6.7
  - decorator=5.1.1
  - eigen=3.4.0
  - executing=0.8.3
  - expat=2.7.1
  - ffmpeg=4.2.2
  - fontconfig=2.14.1
  - fonttools=4.51.0
  - freetype=2.13.3
  - gettext=0.21.0
  - glib=2.78.4
  - glib-tools=2.78.4
  - gmp=6.3.0
  - gnutls=3.6.15
  - graphite2=1.3.14
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - harfbuzz=4.3.0
  - hdf5=1.12.1
  - icu=73.1
  - idna=3.7
  - importlib-metadata=7.0.1
  - importlib_metadata=7.0.1
  - importlib_resources=6.4.0
  - ipykernel=6.29.5
  - ipython=8.12.2
  - jedi=0.19.1
  - joblib=1.4.2
  - jpeg=9e
  - jupyter_client=8.6.0
  - jupyter_core=5.7.2
  - kiwisolver=1.4.4
  - krb5=1.20.1
  - lame=3.100
  - lcms2=2.16
  - lerc=4.0.0
  - libabseil=20240116.2
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libclang=14.0.6
  - libclang13=14.0.6
  - libcurl=8.12.1
  - libcxx=14.0.6
  - libdeflate=1.22
  - libedit=3.1.20230828
  - libev=4.33
  - libffi=3.4.4
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libglib=2.78.4
  - libiconv=1.16
  - libidn2=2.3.4
  - libllvm14=14.0.6
  - libnghttp2=1.57.0
  - libopenblas=0.3.21
  - libopus=1.3.1
  - libpng=1.6.39
  - libpq=17.4
  - libprotobuf=4.25.3
  - libsodium=1.0.18
  - libssh2=1.11.1
  - libtasn1=4.19.0
  - libtiff=4.5.1
  - libunistring=0.9.10
  - libvpx=1.10.0
  - libwebp-base=1.3.2
  - libxml2=2.13.7
  - llvm-openmp=14.0.6
  - lz4-c=1.9.4
  - matplotlib=3.7.2
  - matplotlib-base=3.7.2
  - matplotlib-inline=0.1.6
  - mysql=8.4.0
  - ncurses=6.4
  - nest-asyncio=1.6.0
  - nettle=3.7.3
  - numpy=1.24.3
  - numpy-base=1.24.3
  - opencv=4.10.0
  - openh264=1.8.0
  - openjpeg=2.5.2
  - openldap=2.6.4
  - openssl=3.0.16
  - packaging=24.1
  - parso=0.8.3
  - pcre2=10.42
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pillow=10.4.0
  - pip=24.2
  - pixman=0.40.0
  - platformdirs=3.10.0
  - pooch=1.7.0
  - prompt-toolkit=3.0.43
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.15.1
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.8.20
  - python-dateutil=2.9.0post0
  - pyzmq=25.1.2
  - qt-main=5.15.2
  - readline=8.2
  - requests=2.32.3
  - scikit-learn=1.3.0
  - scipy=1.10.1
  - setuptools=75.1.0
  - six=1.16.0
  - sqlite=3.45.3
  - stack_data=0.2.0
  - threadpoolctl=3.5.0
  - tk=8.6.14
  - tornado=6.4.1
  - traitlets=5.14.3
  - unicodedata2=15.1.0
  - urllib3=2.2.3
  - wcwidth=0.2.5
  - wheel=0.44.0
  - x264=1!152.20180806
  - xz=5.6.4
  - zeromq=4.3.5
  - zipp=3.20.2
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - aiohappyeyeballs==2.4.4
      - aiohttp==3.10.11
      - aiohttp-retry==2.9.1
      - aiosignal==1.3.1
      - amqp==5.3.1
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - appdirs==1.4.4
      - async-timeout==5.0.1
      - asyncssh==2.20.0
      - atpublic==5.0
      - attrs==25.3.0
      - backports-zoneinfo==0.2.1
      - billiard==4.2.1
      - black==24.8.0
      - cachetools==5.5.2
      - celery==5.5.1
      - cffi==1.17.1
      - cfgv==3.4.0
      - click==8.1.8
      - click-didyoumean==0.3.1
      - click-plugins==1.1.1
      - click-repl==0.3.0
      - colorama==0.4.6
      - configobj==5.0.9
      - cryptography==43.0.3
      - dictdiffer==0.9.0
      - diskcache==5.6.3
      - distlib==0.3.9
      - distro==1.9.0
      - dpath==2.2.0
      - dulwich==0.22.4
      - dvc==3.42.0
      - dvc-data==3.8.0
      - dvc-gdrive==3.0.1
      - dvc-http==2.32.0
      - dvc-objects==3.0.6
      - dvc-render==1.0.1
      - dvc-studio-client==0.20.0
      - dvc-task==0.40.2
      - entrypoints==0.4
      - filelock==3.16.1
      - flatten-dict==0.4.2
      - flufl-lock==7.1.1
      - frozenlist==1.5.0
      - fsspec==2025.3.0
      - funcy==2.0
      - gitdb==4.0.12
      - gitpython==3.1.44
      - google-api-core==2.24.2
      - google-api-python-client==2.167.0
      - google-auth==2.39.0
      - google-auth-httplib2==0.2.0
      - googleapis-common-protos==1.70.0
      - grandalf==0.8
      - gto==1.6.2
      - httplib2==0.22.0
      - hydra-core==1.3.2
      - identify==2.6.1
      - isort==5.13.2
      - iterative-stratification==0.1.9
      - iterative-telemetry==0.0.10
      - kombu==5.5.3
      - markdown-it-py==3.0.0
      - mdurl==0.1.2
      - multidict==6.1.0
      - mypy-extensions==1.1.0
      - networkx==3.1
      - nodeenv==1.9.1
      - oauth2client==4.1.3
      - omegaconf==2.3.0
      - orjson==3.10.15
      - pathspec==0.12.1
      - pre-commit==3.5.0
      - propcache==0.2.0
      - proto-plus==1.26.1
      - protobuf==5.29.4
      - pyasn1==0.6.1
      - pyasn1-modules==0.4.2
      - pycparser==2.22
      - pydantic==2.10.6
      - pydantic-core==2.27.2
      - pydot==3.0.4
      - pydrive2==1.21.3
      - pygit2==1.13.3
      - pygtrie==2.5.0
      - pyopenssl==24.2.1
      - pyyaml==6.0.2
      - rich==14.0.0
      - rsa==4.9.1
      - ruamel-yaml==0.18.10
      - ruamel-yaml-clib==0.2.8
      - ruff==0.11.6
      - scmrepo==2.0.4
      - semver==3.0.4
      - shellingham==1.5.4
      - shortuuid==1.0.13
      - shtab==1.7.2
      - smmap==5.0.2
      - sqltrie==0.11.2
      - tabulate==0.9.0
      - tomli==2.2.1
      - tomlkit==0.13.2
      - tqdm==4.67.1
      - typer==0.15.2
      - typing-extensions==4.13.2
      - tzdata==2025.2
      - uritemplate==4.1.1
      - vine==5.1.0
      - virtualenv==20.30.0
      - voluptuous==0.14.2
      - yarl==1.15.2
      - zc-lockfile==3.0.post1
